# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - intubevideo

on:
  push:
    branches:
      - development
  workflow_dispatch:
  
env:
  NODE_VERSION: '20.x'   # Define Node version as environment variable

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: npm install, build, and test
        run: |
          npm ci
          npm run build --if-present
          # Test script fixed to avoid command not found error
          echo "No tests specified" 
          
      - name: Security scan dependencies
        run: |
          npm audit --production --audit-level=high
          # Exit code will be non-zero if high severity vulnerabilities exist

      - name: Zip artifact for deployment
        run: zip -r release.zip ./* -q

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
          retention-days: 1  # Limit retention period for security

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip -q release.zip
      
      # Using fixed version for security and more generic secret names
      - name: Login to Azure
        uses: azure/login@v2.0.0
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_20514E200F934841B95051E8A21BB0DC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B68C060ED2C047C084C0742473AB51A2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_324C597B11624FDE941765FBC04C7ECF }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3.0.0
        with:
          app-name: 'intubevideo'
          slot-name: 'Production'
          package: .
          clean: true
          
      - name: Logout from Azure
        run: |
          az logout